# Generated by Django 5.2.8 on 2025-11-24 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Bo‘lim nomi')),
            ],
            options={
                'verbose_name': 'Katta bo‘lim',
                'verbose_name_plural': 'Katta bo‘limlar',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Rol nomi')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ichki_raqam', models.CharField(max_length=50, verbose_name='Ichki raqam')),
                ('tartib_raqami', models.PositiveIntegerField(verbose_name='Tartib raqami')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_main.bigcategory', verbose_name='Katta bo‘lim')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat nomi')),
                ('file', models.FileField(upload_to='docs/', verbose_name='PDF fayl')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='app_main.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.AddField(
            model_name='bigcategory',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_categories', to='app_main.role', verbose_name='Rolga tegishli'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Telefon raqam')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.role', verbose_name='Foydalanuvchi roli')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
