# Generated by Django 5.2.8 on 2025-11-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ichki_raqam',
            field=models.CharField(max_length=500, verbose_name='Ichki raqam'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tartib_raqami',
            field=models.CharField(max_length=500, verbose_name='Tartib raqami'),
        ),
    ]
