# Generated by Django 5.2.8 on 2025-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_category_ichki_raqam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ichki_raqam',
            field=models.CharField(max_length=500, verbose_name='Indeks raqami'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tartib_raqami',
            field=models.CharField(max_length=500, verbose_name='Yigʻmajild (jild, qism) sarlavhasi'),
        ),
    ]
