# Generated by Django 5.2.8 on 2025-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_category_ichki_raqam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hujjat nomi'),
        ),
    ]
