# Generated by Django 6.0 on 2025-12-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
