# Generated by Django 6.0 on 2025-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_doc_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
